### ISSUE TITLE
Unicode Waterfall

### ISSUE THREAD

**Issue by superteece** [Anonmasky/anonmasky.github.io#1]
Any idea why these characters fail to render in the background but fine everywhere else in the browser?

var randtxt = "🜀🜁🜂🜃🜄🜅🜆🜇🜈🜉🜊🜋🜌"

**Comment by Anonmasky** [comment]
Sorry Sir, I can't figure out how those Unicode works. It can be problem with browser or on those Unicode themselves.

**Comment by superteece** [comment]
It was a font issue.
